### ISSUE TITLE
Correct Data: Wrong title being used when playing video: 6th Jan

### ISSUE THREAD

**Issue by mark-weber** [royaloperahouse/stream-tv-app#122]
The title being displayed when a video starts is different from the title being used on the rest of the screen.
Can we use the same the title?
See Dances at a Gathering (2020).

**Comment by mark-weber** [comment]
![video title](https://user-images.githubusercontent.com/84398423/148059541-ffeca5f2-78f9-4977-a954-6ab4d0718d19.png)

**Comment by YuliyaDmuytrus** [comment]
We had a chat today with James and Maksym Opanasenko and verified the titles pulling from Prismic.
We have found out, that our event titles are pulling correctly - the logic is the following :
- if there is a title in digital event details, then we show it.
- if there is no data from digital events details, then we pull the title from the event details page
- the titles, that we show when the player is showing a video are also correct - they are different from the Event Title by design, as there might be several videos linked to one event.
The same logic is present on the web, so we have replicated it in the TV app. We have also shown the code and confirmed, that the logic is correct. So I guess we do not need extra development efforts on this topic.
