### ISSUE TITLE
Watch now - to replace with 'Continue watching'?

### ISSUE THREAD

**Issue by mark-weber** [royaloperahouse/stream-tv-app#123]
To discuss:
Is it possible to replace 'Watch now' with 'Continue watching' if the item is a continue watching item?

**Comment by sinewave440hz** [comment]
To know if the video is resumable, we need information from prismic that has not yet been received. This info is fetched on pressing the Watch Now button. This in itself would just mean that we split the function that does that into smaller parts. But the function that does that also shows a dialog if it is discovered that the user is not subscribed.

In short, we would need to show the unsubscribed dialog on entering the event details screen in order to do this. Not sure about the UX. What do you think @mark-weber?

**Comment by sinewave440hz** [comment]
(It was situations like this that led me to originally fetch the urls in the background, but we can probably find a way to work around this)

**Comment by sinewave440hz** [comment]
(We actually have the resume time stored locally, but we retrieve the ids from Prismic that allow us to identify the resume time in question when we press the watch now button...)

**Comment by mark-weber** [comment]
A user would only be able to watch content if either (1) they are subscribed or (2) they have paid for that item as PPV.
What feeds the 'continue watching' rail? This appears regardless of pressing the play button...

**Comment by sinewave440hz** [comment]
Yes, good point. I can at least use the fact that we came from the Continue Watching rail to show the Continue Watching text. I'll have a think about how to show Continue Watching when we come from other rails.

**Comment by sinewave440hz** [comment]
Ok, the fact that we are/can be in a state in the app where we have a video in the "Continue watching" at the same time as being unsubscribed - that is probably an edge case, really, right?

I did as I mentioned in the previous comment and just checked if we are coming from the "Continue watching" rail. For other videos, I make a call to prismic. If the user is unsubscribed, the prismic call concludes silently. If subscribed, we fetch the necessary ids so that we can establish whether or not the video has been played.

The call is actually the first part of what happens when we press the "Watch now" option. I tried to optimise by saving the result of this call, but it got a bit too complicated because of several other things that the call to get the performance video does. So I think that's best left for another time.

Note that the data shown in the "Continue watching"-rail just fetches all "Continue Watching" videos. To actually identify a specific "Continue watching" video, we need the ids that we retrieve as described above. At least, that's the way the app works now...

I hope that's clear :)

**Comment by mark-weber** [comment]
@sinewave440hz there is the situation where someone has paid for a video as a PPV, and that may also have 'continue watching'. However with both of these there is the potential that selecting to play wont work, because either since they started their subscription has ended or the PPV rental window has closed.

**Comment by mark-weber** [comment]
.. but I think its fine for them to discover that after clicking 'continue watching'!

**Comment by sinewave440hz** [comment]
Good point again. This current solution should work fine in the PPV
situation too, when it’s implemented 👍

**Comment by sinewave440hz** [comment]
Just for clarity: This issue is done and awaiting review and merge.
